### ISSUE TITLE
Editing ReadME to address compatibility issues

### ISSUE THREAD

**Issue by pranathibora14** [utkarshpant/telemetry#3]
Need to edit the ReadME file to address the compatibility issues for C++ version <11. It did not work for me initially since I was working on C++98. I believe it can be a useful addition.

**Comment by utkarshpant** [comment]
@pranathibora14 That is right. Could you take a look and figure out the fix?

**Comment by pranathibora14** [comment]
Sure. It's an easy fix. I'll do it.

**Comment by utkarshpant** [comment]
Thanks for the help @pranathibora14. Closed the issue. 🥇
