### ISSUE TITLE
Write destructors for each container.

### ISSUE THREAD

**Issue by utkarshpant** [utkarshpant/telemetry#6]
Destructors have to be written for each container, to enable the following behaviors when an object is ```deleted```:

1. In the **List** class, the ```node_count``` counter should be decremented after the destructor of the **Node** class is called due to the ```delete``` keyword. Since **Stack** and **Queue** depend on the **List** class (for now at least) for the underlying container, the addition of a destructor affects them too (in removal operations like ```pop()``` and ```size()```).

**Comment by zg3d** [comment]
Hey, I can take a look  at this issue.

**Comment by utkarshpant** [comment]
> Hey, I can take a look  at this issue.

Sure @zg3d. I can assign this issue to you if you've gotten familiar with the repository. Since this has been a largely personal effort, I'd be happy to help if you need clarifications anywhere.
